// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: esp_rmaker_prov_local_ctrl.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

enum RmakerProvLocalCtrl_RMakerLocalCtrlStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case success // = 0
  case fail // = 1
  case invalidParam // = 2
  case noMemory // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .success
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .success
    case 1: self = .fail
    case 2: self = .invalidParam
    case 3: self = .noMemory
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .success: return 0
    case .fail: return 1
    case .invalidParam: return 2
    case .noMemory: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RmakerProvLocalCtrl_RMakerLocalCtrlStatus] = [
    .success,
    .fail,
    .invalidParam,
    .noMemory,
  ]

}

enum RmakerProvLocalCtrl_RMakerLocalCtrlDataType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case typeParams // = 0
  case typeConfig // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .typeParams
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .typeParams
    case 1: self = .typeConfig
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .typeParams: return 0
    case .typeConfig: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RmakerProvLocalCtrl_RMakerLocalCtrlDataType] = [
    .typeParams,
    .typeConfig,
  ]

}

enum RmakerProvLocalCtrl_RMakerLocalCtrlMsgType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case typeCmdGetData // = 0
  case typeRespGetData // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .typeCmdGetData
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .typeCmdGetData
    case 1: self = .typeRespGetData
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .typeCmdGetData: return 0
    case .typeRespGetData: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [RmakerProvLocalCtrl_RMakerLocalCtrlMsgType] = [
    .typeCmdGetData,
    .typeRespGetData,
  ]

}

struct RmakerProvLocalCtrl_PayloadBuf: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var offset: UInt32 = 0

  var payload: Data = Data()

  var totalLen: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Command to get data (params or config) - contains offset to request next chunk 
struct RmakerProvLocalCtrl_CmdGetData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var dataType: RmakerProvLocalCtrl_RMakerLocalCtrlDataType = .typeParams

  var offset: UInt32 = 0

  /// Optional timestamp for signed response 
  var timestamp: Int64 = 0

  /// Flag to indicate if timestamp is provided (since 0 is a valid timestamp) 
  var hasTimestamp_p: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Response with data (params or config) 
struct RmakerProvLocalCtrl_RespGetData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var status: RmakerProvLocalCtrl_RMakerLocalCtrlStatus = .success

  var buf: RmakerProvLocalCtrl_PayloadBuf {
    get {return _buf ?? RmakerProvLocalCtrl_PayloadBuf()}
    set {_buf = newValue}
  }
  /// Returns true if `buf` has been explicitly set.
  var hasBuf: Bool {return self._buf != nil}
  /// Clears the value of `buf`. Subsequent reads from it will return its default value.
  mutating func clearBuf() {self._buf = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _buf: RmakerProvLocalCtrl_PayloadBuf? = nil
}

struct RmakerProvLocalCtrl_RMakerLocalCtrlPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var msg: RmakerProvLocalCtrl_RMakerLocalCtrlMsgType = .typeCmdGetData

  var payload: RmakerProvLocalCtrl_RMakerLocalCtrlPayload.OneOf_Payload? = nil

  var cmdGetData: RmakerProvLocalCtrl_CmdGetData {
    get {
      if case .cmdGetData(let v)? = payload {return v}
      return RmakerProvLocalCtrl_CmdGetData()
    }
    set {payload = .cmdGetData(newValue)}
  }

  var respGetData: RmakerProvLocalCtrl_RespGetData {
    get {
      if case .respGetData(let v)? = payload {return v}
      return RmakerProvLocalCtrl_RespGetData()
    }
    set {payload = .respGetData(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Payload: Equatable, Sendable {
    case cmdGetData(RmakerProvLocalCtrl_CmdGetData)
    case respGetData(RmakerProvLocalCtrl_RespGetData)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rmaker_prov_local_ctrl"

extension RmakerProvLocalCtrl_RMakerLocalCtrlStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Success"),
    1: .same(proto: "Fail"),
    2: .same(proto: "InvalidParam"),
    3: .same(proto: "NoMemory"),
  ]
}

extension RmakerProvLocalCtrl_RMakerLocalCtrlDataType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "TypeParams"),
    1: .same(proto: "TypeConfig"),
  ]
}

extension RmakerProvLocalCtrl_RMakerLocalCtrlMsgType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "TypeCmdGetData"),
    1: .same(proto: "TypeRespGetData"),
  ]
}

extension RmakerProvLocalCtrl_PayloadBuf: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PayloadBuf"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Offset"),
    2: .same(proto: "Payload"),
    3: .same(proto: "TotalLen"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.offset) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.totalLen) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.offset != 0 {
      try visitor.visitSingularUInt32Field(value: self.offset, fieldNumber: 1)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 2)
    }
    if self.totalLen != 0 {
      try visitor.visitSingularUInt32Field(value: self.totalLen, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerProvLocalCtrl_PayloadBuf, rhs: RmakerProvLocalCtrl_PayloadBuf) -> Bool {
    if lhs.offset != rhs.offset {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.totalLen != rhs.totalLen {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerProvLocalCtrl_CmdGetData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CmdGetData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "DataType"),
    2: .same(proto: "Offset"),
    3: .same(proto: "Timestamp"),
    4: .same(proto: "HasTimestamp"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.dataType) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.offset) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.timestamp) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.hasTimestamp_p) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dataType != .typeParams {
      try visitor.visitSingularEnumField(value: self.dataType, fieldNumber: 1)
    }
    if self.offset != 0 {
      try visitor.visitSingularUInt32Field(value: self.offset, fieldNumber: 2)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.timestamp, fieldNumber: 3)
    }
    if self.hasTimestamp_p != false {
      try visitor.visitSingularBoolField(value: self.hasTimestamp_p, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerProvLocalCtrl_CmdGetData, rhs: RmakerProvLocalCtrl_CmdGetData) -> Bool {
    if lhs.dataType != rhs.dataType {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.hasTimestamp_p != rhs.hasTimestamp_p {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerProvLocalCtrl_RespGetData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RespGetData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Status"),
    2: .same(proto: "Buf"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._buf) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.status != .success {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    try { if let v = self._buf {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerProvLocalCtrl_RespGetData, rhs: RmakerProvLocalCtrl_RespGetData) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs._buf != rhs._buf {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RmakerProvLocalCtrl_RMakerLocalCtrlPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RMakerLocalCtrlPayload"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "msg"),
    10: .same(proto: "cmdGetData"),
    11: .same(proto: "respGetData"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.msg) }()
      case 10: try {
        var v: RmakerProvLocalCtrl_CmdGetData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .cmdGetData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .cmdGetData(v)
        }
      }()
      case 11: try {
        var v: RmakerProvLocalCtrl_RespGetData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .respGetData(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .respGetData(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.msg != .typeCmdGetData {
      try visitor.visitSingularEnumField(value: self.msg, fieldNumber: 1)
    }
    switch self.payload {
    case .cmdGetData?: try {
      guard case .cmdGetData(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .respGetData?: try {
      guard case .respGetData(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: RmakerProvLocalCtrl_RMakerLocalCtrlPayload, rhs: RmakerProvLocalCtrl_RMakerLocalCtrlPayload) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
